import WebApp from '@twa-dev/sdk';

export interface ShameCardOptions {
  categoryEmoji: string;
  categoryName: string;
  amount: number;
  monthLabel: string;
  projection?: number;
}

/**
 * Generate a canvas-based shame card image.
 * Returns a Blob (PNG) that can be shared.
 */
export async function generateShameCardImage(
  options: ShameCardOptions
): Promise<Blob> {
  const { categoryEmoji, categoryName, amount, monthLabel, projection } = options;

  const width = 800;
  const height = 600;
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d')!;

  // Background: dark theme
  ctx.fillStyle = '#1c1c1e';
  ctx.fillRect(0, 0, width, height);

  // Subtle gradient overlay
  const grad = ctx.createLinearGradient(0, 0, width, height);
  grad.addColorStop(0, '#2c2c2e');
  grad.addColorStop(1, '#1c1c1e');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, width, height);

  // Category emoji (top)
  ctx.font = '120px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText(categoryEmoji, width / 2, height * 0.25);

  // Category name
  ctx.font = 'bold 36px sans-serif';
  ctx.fillStyle = '#8e8e93';
  ctx.fillText(categoryName.toUpperCase(), width / 2, height * 0.35);

  // Amount (big)
  ctx.font = 'bold 80px sans-serif';
  ctx.fillStyle = '#ffffff';
  ctx.fillText(`$${amount.toFixed(2)}`, width / 2, height * 0.55);

  // Month label
  ctx.font = '24px sans-serif';
  ctx.fillStyle = '#8e8e93';
  ctx.fillText(monthLabel, width / 2, height * 0.65);

  // Projection if provided
  if (projection !== undefined) {
    ctx.font = '20px sans-serif';
    ctx.fillStyle = '#ff3b30';
    ctx.fillText(`Projected annual: $${projection.toFixed(2)}`, width / 2, height * 0.78);
  }

  // Add bottom shame note
  ctx.font = 'italic 20px sans-serif';
  ctx.fillStyle = '#636366';
  ctx.fillText('Generated by Anti-Budget', width / 2, height * 0.92);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      resolve(blob!);
    }, 'image/png');
  });
}

/**
 * Share shame card via Telegram or clipboard fallback.
 */
export async function shareShameCard(options: ShameCardOptions): Promise<void> {
  const blob = await generateShameCardImage(options);
  const url = URL.createObjectURL(blob);

  try {
    // Build text message
    const text = options.projection
      ? `Anti-Budget shame: $${options.amount} on ${options.categoryName} (${options.monthLabel}). Projected annual: $${options.projection.toFixed(2)}`
      : `I spent $${options.amount} on ${options.categoryName} in ${options.monthLabel}!`;

    // Use Telegram WebApp if available
    if (WebApp && typeof WebApp.MainButton === 'object') {
      // Telegram mini app available - clipboard fallback
      try {
        await navigator.clipboard.writeText(text);
        WebApp.showAlert('Shame stats copied to clipboard!');
        return;
      } catch {
        // Fallback to alert
      }
    }

    // Fallback: copy to clipboard
    await navigator.clipboard.writeText(text);
    alert('Shame stats copied to clipboard!');
  } finally {
    URL.revokeObjectURL(url);
  }
}